
# Database connection
datasource:
  url: jdbc:postgresql://localhost:5432/task_manager
  username: admin
  password: password
  driver-class-name: org.postgresql.Driver # optional (Boot can infer from URL)

jpa:
  hibernate:
    ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect