spring:
  application:
    name: task-manager
  datasource:
    url: jdbc:h2:mem:task-manager
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
  jpa.hibernate.ddl-auto: update
  h2:
    console:
      path: /h2-console